sonar.projectKey=gurvan-le-pape_beyond-the-arc
sonar.projectName=beyond-the-arc
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/coverage/**,**/out/**,**/.git/**,**/.venv/**,**/venv/**,**/migrations/**
sonar.cpd.exclusions=src/frontend/i18n.ts