sonar.projectKey=gurvan-le-pape_beyond-the-arc
sonar.organization=gurvan-le-pape
sonar.projectName=Beyond The Arc

# Sources
sonar.sources=src

# Coverage
sonar.javascript.lcov.reportPaths=src/backend/coverage/lcov.info

# Exclusions
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/*.spec.ts,**/*.test.ts
sonar.coverage.exclusions=**/*.spec.ts,**/*.test.ts,**/dto/**,**/types/**