// src/frontend/shared/components/ui/primitives/index.ts
/**
 * @file Automatically generated by barrelsby.
 */

export * from "./Badge";
export * from "./Button";
export * from "./Card";
export * from "./Switch";
export * from "./Table";
