INSERT INTO clubs (zip_code, code, name, city, committee_id)
VALUES
    ('04400', 'SUD0004007', 'Entente Blanche Ubaye', 'BARCELONNETTE', (SELECT id FROM committees WHERE name = 'COMITE DES ALPES-DE-HAUTE-PROVENCE DE BASKET-BALL')),
    ('04160', 'SUD0004104', 'US CHATEAU ARNOUX ST AUBAN', 'CHATEAU-ARNOUX', (SELECT id FROM committees WHERE name = 'COMITE DES ALPES-DE-HAUTE-PROVENCE DE BASKET-BALL')),
    ('04100', 'SUD0004106', 'HAUTE PROVENCE BASKET', 'MANOSQUE', (SELECT id FROM committees WHERE name = 'COMITE DES ALPES-DE-HAUTE-PROVENCE DE BASKET-BALL')),
    ('04140', 'SUD0004107', 'US SEYNE LES ALPES', 'SEYNE', (SELECT id FROM committees WHERE name = 'COMITE DES ALPES-DE-HAUTE-PROVENCE DE BASKET-BALL')),
    ('04200', 'SUD0004112', 'SISTERON BC', 'SISTERON', (SELECT id FROM committees WHERE name = 'COMITE DES ALPES-DE-HAUTE-PROVENCE DE BASKET-BALL')),
    ('04000', 'SUD0004113', 'DIGNE LES BAINS BASKET CLUB', 'DIGNE-LES-BAINS', (SELECT id FROM committees WHERE name = 'COMITE DES ALPES-DE-HAUTE-PROVENCE DE BASKET-BALL')),
    ('04400', 'SUD0004114', 'BASKET CLUB BARCELONNETTE', 'THUILES', (SELECT id FROM committees WHERE name = 'COMITE DES ALPES-DE-HAUTE-PROVENCE DE BASKET-BALL')),
    ('04700', 'SUD0004116', 'CLUB BASKET BALL FORCALQUIER', 'ORAISON', (SELECT id FROM committees WHERE name = 'COMITE DES ALPES-DE-HAUTE-PROVENCE DE BASKET-BALL'));