INSERT INTO clubs (zip_code, code, name, city, committee_id)
VALUES
    ('05000', 'SUD0005002', 'CD HORS ASSOCIATION', 'GAP', (SELECT id FROM committees WHERE name = 'COMITE DES HAUTES-ALPES DE BASKET-BALL')),
    ('05000', 'SUD0005006', 'Entente Charance - Le Piolit', 'GAP', (SELECT id FROM committees WHERE name = 'COMITE DES HAUTES-ALPES DE BASKET-BALL')),
    ('05500', 'SUD0005008', 'Entente BBCV GASB05', 'SAINT-BONNET-EN-CHAMPSAUR', (SELECT id FROM committees WHERE name = 'COMITE DES HAUTES-ALPES DE BASKET-BALL')),
    ('05100', 'SUD0005202', 'BRIANCON BASKET BALL', 'BRIANCON', (SELECT id FROM committees WHERE name = 'COMITE DES HAUTES-ALPES DE BASKET-BALL')),
    ('05000', 'SUD0005204', 'GAP ALPES DU SUD BASKET 05', 'GAP', (SELECT id FROM committees WHERE name = 'COMITE DES HAUTES-ALPES DE BASKET-BALL')),
    ('05300', 'SUD0005206', 'LARAGNE SPORTS BASKET', 'LARAGNE-MONTEGLIN', (SELECT id FROM committees WHERE name = 'COMITE DES HAUTES-ALPES DE BASKET-BALL')),
    ('05400', 'SUD0005208', 'US VEYNES SNCF SECTION BASKET-B.', 'VEYNES', (SELECT id FROM committees WHERE name = 'COMITE DES HAUTES-ALPES DE BASKET-BALL')),
    ('05500', 'SUD0005209', 'BB CHAMPSAUR VALGAUDEMAR', 'SAINT-BONNET-EN-CHAMPSAUR', (SELECT id FROM committees WHERE name = 'COMITE DES HAUTES-ALPES DE BASKET-BALL')),
    ('05200', 'SUD0005210', 'BASKETBALL EMBRUNAIS', 'EMBRUN', (SELECT id FROM committees WHERE name = 'COMITE DES HAUTES-ALPES DE BASKET-BALL')),
    ('05230', 'SUD0005215', 'BATIE BASKET CLUB', 'LABATIE-NEUVE', (SELECT id FROM committees WHERE name = 'COMITE DES HAUTES-ALPES DE BASKET-BALL'));