INSERT INTO clubs (code, name, zip_code, city, committee_id)
VALUES
    ('GES0008001', 'CD 08 HORS ASSOCIATION', '08000', 'CHARLEVILLE-MEZIERES', (SELECT id FROM committees WHERE name = 'COMITE DES ARDENNES DE BASKET-BALL')),
    ('GES0008002', 'BASKET CLUB BARAQUIN', '08800', 'MONTHERME', (SELECT id FROM committees WHERE name = 'COMITE DES ARDENNES DE BASKET-BALL')),
    ('GES0008004', 'FLAMMES CAROLO BASKET ARDENNES', '08000', 'CHARLEVILLE-MEZIERES', (SELECT id FROM committees WHERE name = 'COMITE DES ARDENNES DE BASKET-BALL')),
    ('GES0008005', 'ETOILE DE CHARLEVILLE MEZIERES', '08000', 'CHARLEVILLE-MEZIERES', (SELECT id FROM committees WHERE name = 'COMITE DES ARDENNES DE BASKET-BALL')),
    ('GES0008011', 'BASKET CLUB GIVETOIS', '08600', 'GIVET', (SELECT id FROM committees WHERE name = 'COMITE DES ARDENNES DE BASKET-BALL')),
    ('GES0008012', 'BASKET CLUB DE HARAUCOURT', '08450', 'HARAUCOURT', (SELECT id FROM committees WHERE name = 'COMITE DES ARDENNES DE BASKET-BALL')),
    ('GES0008013', 'UNION SPORTIVE DE LAIFOUR', '08800', 'LAIFOUR', (SELECT id FROM committees WHERE name = 'COMITE DES ARDENNES DE BASKET-BALL')),
    ('GES0008016', 'AMICAL CLUB MOUZONNAIS', '08210', 'MOUZON', (SELECT id FROM committees WHERE name = 'COMITE DES ARDENNES DE BASKET-BALL')),
    ('GES0008018', 'RETHEL SPORTIF BASKET', '08300', 'RETHEL', (SELECT id FROM committees WHERE name = 'COMITE DES ARDENNES DE BASKET-BALL')),
    ('GES0008019', 'MARCASSINS DE REVIN', '08500', 'REVIN', (SELECT id FROM committees WHERE name = 'COMITE DES ARDENNES DE BASKET-BALL')),
    ('GES0008021', 'BASKET CLUB SEDANAIS', '08200', 'SEDAN', (SELECT id FROM committees WHERE name = 'COMITE DES ARDENNES DE BASKET-BALL')),
    ('GES0008024', 'EA VAILLANTE VRIGNE AUX BOIS', '08330', 'VRIGNE AUX BOIS', (SELECT id FROM committees WHERE name = 'COMITE DES ARDENNES DE BASKET-BALL')),
    ('GES0008033', 'VIREUX BASKET CLUB', '08320', 'VIREUX-WALLERAND', (SELECT id FROM committees WHERE name = 'COMITE DES ARDENNES DE BASKET-BALL')),
    ('GES0008034', 'VILLERS SEMEUSE BASKET', '08000', 'VILLERS-SEMEUSE', (SELECT id FROM committees WHERE name = 'COMITE DES ARDENNES DE BASKET-BALL'));
