INSERT INTO clubs (code, name, zip_code, city, committee_id)
VALUES
    ('OCC0009001', 'CD HORS ASSOCIATION', '09100', 'PAMIERS', (SELECT id FROM committees WHERE name = 'COMITE DE L''ARIEGE DE BASKET-BALL')),
    ('OCC0009002', 'UN. OL. DE PAMIERS', '09100', 'PAMIERS', (SELECT id FROM committees WHERE name = 'COMITE DE L''ARIEGE DE BASKET-BALL')),
    ('OCC0009003', 'COQUELICOT LEZATOIS', '09210', 'LEZAT-SUR-LEZE', (SELECT id FROM committees WHERE name = 'COMITE DE L''ARIEGE DE BASKET-BALL')),
    ('OCC0009004', 'STADE LAVELANETIEN BASKET', '09300', 'LAVELANET', (SELECT id FROM committees WHERE name = 'COMITE DE L''ARIEGE DE BASKET-BALL')),
    ('OCC0009006', 'LE COQ CARLANAIS', '09130', 'CARLA BAYLE', (SELECT id FROM committees WHERE name = 'COMITE DE L''ARIEGE DE BASKET-BALL')),
    ('OCC0009007', 'U.A. SAVERDUNOISE BASKET', '09700', 'SAVERDUN', (SELECT id FROM committees WHERE name = 'COMITE DE L''ARIEGE DE BASKET-BALL')),
    ('OCC0009012', 'BASKET CLUB VARILHOIS', '09120', 'VARILHES', (SELECT id FROM committees WHERE name = 'COMITE DE L''ARIEGE DE BASKET-BALL')),
    ('OCC0009015', 'SAINT GIRONS BASKET CLUB', '09200', 'SAINT-GIRONS', (SELECT id FROM committees WHERE name = 'COMITE DE L''ARIEGE DE BASKET-BALL')),
    ('OCC0009022', 'PAYS DE FOIX BASKET', '09000', 'VERNAJOUL', (SELECT id FROM committees WHERE name = 'COMITE DE L''ARIEGE DE BASKET-BALL')),
    ('OCC0009030', 'ENT FOIX PAMIERS BASKET', '09000', 'VERNAJOUL', (SELECT id FROM committees WHERE name = 'COMITE DE L''ARIEGE DE BASKET-BALL')),
    ('OCC0009056', 'MAZERES BASKET CLUB', '09270', 'MAZERES', (SELECT id FROM committees WHERE name = 'COMITE DE L''ARIEGE DE BASKET-BALL'));
