INSERT INTO clubs (zip_code, code, name, city, committee_id)
VALUES
    ('10000', 'GES0010001', 'CD HORS ASSOCIATION - COMITE DE L''AUBE', 'TROYES', (SELECT id FROM committees WHERE name = 'COMITE DE L''AUBE DE BASKET-BALL')),
    ('10150', 'GES0010003', 'BASKET CLUB COEURLEQUIN', 'CRENEY-PRES-TROYES', (SELECT id FROM committees WHERE name = 'COMITE DE L''AUBE DE BASKET-BALL')),
    ('10100', 'GES0010005', 'ASF ROMILLY', 'ROMILLY-SUR-SEINE', (SELECT id FROM committees WHERE name = 'COMITE DE L''AUBE DE BASKET-BALL')),
    ('10300', 'GES0010007', 'SAINTE SAVINE BASKET', 'SAINTE-SAVINE', (SELECT id FROM committees WHERE name = 'COMITE DE L''AUBE DE BASKET-BALL')),
    ('10400', 'GES0010009', 'ESPERANCE NOGENT SUR SEINE', 'NOGENT-SUR-SEINE', (SELECT id FROM committees WHERE name = 'COMITE DE L''AUBE DE BASKET-BALL')),
    ('10120', 'GES0010012', 'BC SAINT ANDRE LES VERGERS', 'SAINT-ANDRE-LES-VERGERS', (SELECT id FROM committees WHERE name = 'COMITE DE L''AUBE DE BASKET-BALL')),
    ('10000', 'GES0010013', 'BASKET SANCEO TROYEN', 'TROYES', (SELECT id FROM committees WHERE name = 'COMITE DE L''AUBE DE BASKET-BALL')),
    ('10370', 'GES0010014', 'UNION SPORTIVE VILLENAUXE LA GRANDE BASKETBALL (USV BASKET)', 'VILLENAUXE-LA-GRANDE', (SELECT id FROM committees WHERE name = 'COMITE DE L''AUBE DE BASKET-BALL')),
    ('10000', 'GES0010015', 'ENERGIE TROYENNE', 'TROYES', (SELECT id FROM committees WHERE name = 'COMITE DE L''AUBE DE BASKET-BALL')),
    ('10350', 'GES0010019', 'MJC MARIGNY LE CHATEL', 'MARIGNY-LE-CHATEL', (SELECT id FROM committees WHERE name = 'COMITE DE L''AUBE DE BASKET-BALL')),
    ('10200', 'GES0010021', 'PATRONAGE LAIQUE BAR SUR AUBE', 'BAR-SUR-AUBE', (SELECT id FROM committees WHERE name = 'COMITE DE L''AUBE DE BASKET-BALL')),
    ('10600', 'GES0010028', 'A. J. FERRY. F. BUISSON BASKET', 'LA CHAPELLE-SAINT-LUC', (SELECT id FROM committees WHERE name = 'COMITE DE L''AUBE DE BASKET-BALL')),
    ('10170', 'GES0010031', 'MERY BASKET CLUB', 'MERY-SUR-SEINE', (SELECT id FROM committees WHERE name = 'COMITE DE L''AUBE DE BASKET-BALL')),
    ('10000', 'GES0010032', 'FRIENDS BASKETBALL TEAM', 'TROYES', (SELECT id FROM committees WHERE name = 'COMITE DE L''AUBE DE BASKET-BALL')),
    ('10000', 'GES0010034', 'ASSOCIATION BASKETBALL DES CHARTREUX (A.B.C)', 'TROYES', (SELECT id FROM committees WHERE name = 'COMITE DE L''AUBE DE BASKET-BALL')),
    ('10600', 'GES0010035', 'ASSOCIATION SPORTIVE PAYNS BASKET (ASPB)', 'PAYNS', (SELECT id FROM committees WHERE name = 'COMITE DE L''AUBE DE BASKET-BALL')),
    ('10140', 'GES0010037', 'BASKET CLUB VENDEUVRE', 'VENDEUVRE-SUR-BARSE', (SELECT id FROM committees WHERE name = 'COMITE DE L''AUBE DE BASKET-BALL'));