INSERT INTO clubs (code, zip_code, name, city, committee_id)
VALUES
    ('OCC0011010', '11300', 'BASKET CLUB LIMOUXIN', 'LIMOUX', (SELECT id FROM committees WHERE name = 'COMITE DE L''AUDE DE BASKET-BALL')),
    ('OCC0011012', '11600', 'SO CARCASSONNE', 'CONQUES-SUR-ORBIEL', (SELECT id FROM committees WHERE name = 'COMITE DE L''AUDE DE BASKET-BALL')),
    ('OCC0011013', '11110', 'SO COURSAN - Gd NARBONNE', 'COURSAN', (SELECT id FROM committees WHERE name = 'COMITE DE L''AUDE DE BASKET-BALL')),
    ('OCC0011017', '11200', 'LEZI BASKET', 'LEZIGNAN-CORBIERES', (SELECT id FROM committees WHERE name = 'COMITE DE L''AUDE DE BASKET-BALL')),
    ('OCC0011018', '11100', 'BC NARBONNE MEDITERRANEE', 'NARBONNE', (SELECT id FROM committees WHERE name = 'COMITE DE L''AUDE DE BASKET-BALL')),
    ('OCC0011024', '11400', 'BO CASTELNAUDARY', 'CASTELNAUDARY', (SELECT id FROM committees WHERE name = 'COMITE DE L''AUDE DE BASKET-BALL')),
    ('OCC0011030', '11130', 'SAS SIGEAN', 'SIGEAN', (SELECT id FROM committees WHERE name = 'COMITE DE L''AUDE DE BASKET-BALL')),
    ('OCC0011032', '11120', 'BC SUD MINERVOIS', 'SAINT-NAZAIRE-D''AUDE', (SELECT id FROM committees WHERE name = 'COMITE DE L''AUDE DE BASKET-BALL'));