INSERT INTO clubs (code, name, zip_code, city, committee_id)
VALUES
    ('ARA0015001', 'CD 15 HORS ASSOCIATION', '15000', 'AURILLAC', (SELECT id FROM committees WHERE name = 'COMITE DU CANTAL DE BASKET-BALL')),
    ('ARA0015004', 'CANTALIENNE AURILLAC', '15000', 'AURILLAC', (SELECT id FROM committees WHERE name = 'COMITE DU CANTAL DE BASKET-BALL')),
    ('ARA0015006', 'SANFLORAINE BASKET-BALL', '15100', 'SAINT-FLOUR', (SELECT id FROM committees WHERE name = 'COMITE DU CANTAL DE BASKET-BALL')),
    ('ARA0015007', 'AFR BASKET PIERREFORT', '15230', 'PIERREFORT', (SELECT id FROM committees WHERE name = 'COMITE DU CANTAL DE BASKET-BALL')),
    ('ARA0015008', 'NAUCELLES BASKET ASSOCIATION', '15250', 'NAUCELLES', (SELECT id FROM committees WHERE name = 'COMITE DU CANTAL DE BASKET-BALL')),
    ('ARA0015010', 'BASKET CLUB DU CARLADEZ', '15130', 'VEZELS-ROUSSY', (SELECT id FROM committees WHERE name = 'COMITE DU CANTAL DE BASKET-BALL'));
