INSERT INTO clubs (code, name, zip_code, city, committee_id)
VALUES
    ('NAQ0019002', 'ARGENTAT BASKET CLUB', '19400', 'Argentat-sur-Dordogne', (SELECT id FROM committees WHERE name = 'COMITE DE LA CORREZE DE BASKET-BALL')),
    ('NAQ0019003', 'UNION SPORTIVE BEAULIEU BASKET', '19120', 'BEAULIEU-SUR-DORDOGNE', (SELECT id FROM committees WHERE name = 'COMITE DE LA CORREZE DE BASKET-BALL')),
    ('NAQ0019005', 'CA BRIVE CORREZE SECTION BASKET', '19100', 'BRIVE-LA-GAILLARDE', (SELECT id FROM committees WHERE name = 'COMITE DE LA CORREZE DE BASKET-BALL')),
    ('NAQ0019007', 'BASKET BALL AUVEZERE', '19210', 'LUBERSAC', (SELECT id FROM committees WHERE name = 'COMITE DE LA CORREZE DE BASKET-BALL')),
    ('NAQ0019012', 'AS SAINT PANTALEON', '19600', 'SAINT-PANTALEON-DE-LARCHE', (SELECT id FROM committees WHERE name = 'COMITE DE LA CORREZE DE BASKET-BALL')),
    ('NAQ0019014', 'UNION SPORTIVE TULLE CORREZE', '19000', 'TULLE', (SELECT id FROM committees WHERE name = 'COMITE DE LA CORREZE DE BASKET-BALL')),
    ('NAQ0019015', 'BASKET CLUB UZERCHOIS', '19140', 'UZERCHE', (SELECT id FROM committees WHERE name = 'COMITE DE LA CORREZE DE BASKET-BALL')),
    ('NAQ0019016', 'CD19 HORS ASSOCIATION - CORREZE', '19000', 'TULLE', (SELECT id FROM committees WHERE name = 'COMITE DE LA CORREZE DE BASKET-BALL')),
    ('NAQ0019017', 'SEILHAC ATHLETIC CLUB', '19700', 'SEILHAC', (SELECT id FROM committees WHERE name = 'COMITE DE LA CORREZE DE BASKET-BALL')),
    ('NAQ0019018', 'USSEL BASKET CLUB', '19200', 'USSEL', (SELECT id FROM committees WHERE name = 'COMITE DE LA CORREZE DE BASKET-BALL')),
    ('NAQ0019020', 'DYNAMIC BASKET LOT CORREZE', '19500', 'MEYSSAC', (SELECT id FROM committees WHERE name = 'COMITE DE LA CORREZE DE BASKET-BALL')),
    ('NAQ0019029', 'BASKET CLUB MARCILLAC', '19320', 'CHAMPAGNAC-LA-NOAILLE', (SELECT id FROM committees WHERE name = 'COMITE DE LA CORREZE DE BASKET-BALL'));
