INSERT INTO clubs (code, name, zip_code, city, committee_id)
VALUES
    ('NAQ0023001', 'Comité départemental de basket de la Creuse', '23000', 'GUERET', (SELECT id FROM committees WHERE name = 'COMITE DE LA CREUSE DE BASKET-BALL')),
    ('NAQ0023002', 'Aubusson felletin Basket', '23200', 'AUBUSSON', (SELECT id FROM committees WHERE name = 'COMITE DE LA CREUSE DE BASKET-BALL')),
    ('NAQ0023003', 'AMICALE LAIQUE BENEVENT', '23210', 'BENEVENT-L''ABBAYE', (SELECT id FROM committees WHERE name = 'COMITE DE LA CREUSE DE BASKET-BALL')),
    ('NAQ0023006', 'BASKET CLUB DUNOIS', '23800', 'DUN-LE-PALESTEL', (SELECT id FROM committees WHERE name = 'COMITE DE LA CREUSE DE BASKET-BALL')),
    ('NAQ0023007', 'AEL GUERET', '23000', 'GUERET', (SELECT id FROM committees WHERE name = 'COMITE DE LA CREUSE DE BASKET-BALL')),
    ('NAQ0023008', 'AMICALE LAIQUE LAVAUFRANCHE', '23600', 'LAVAUFRANCHE', (SELECT id FROM committees WHERE name = 'COMITE DE LA CREUSE DE BASKET-BALL')),
    ('NAQ0023015', 'BASKET CLUB AUZANCES', '23700', 'AUZANCES', (SELECT id FROM committees WHERE name = 'COMITE DE LA CREUSE DE BASKET-BALL')),
    ('NAQ0023017', 'SOCIETE SPORTIVE DE BONNAT BASKET-BALL', '23220', 'BONNAT', (SELECT id FROM committees WHERE name = 'COMITE DE LA CREUSE DE BASKET-BALL')),
    ('NAQ0023018', 'BASKET-BALL SAINTE-FEYROIS', '23000', 'SAINTE-FEYRE', (SELECT id FROM committees WHERE name = 'COMITE DE LA CREUSE DE BASKET-BALL')),
    ('NAQ0023020', 'BASKETBALL AHUNOIS', '23150', 'AHUN', (SELECT id FROM committees WHERE name = 'COMITE DE LA CREUSE DE BASKET-BALL')),
    ('NAQ0023023', 'LA SOUTERRAINE BASKET BALL', '23300', 'LA SOUTERRAINE', (SELECT id FROM committees WHERE name = 'COMITE DE LA CREUSE DE BASKET-BALL')),
    ('NAQ0023026', 'BOURGANEUF BASKET CLUB', '23400', 'BOURGANEUF', (SELECT id FROM committees WHERE name = 'COMITE DE LA CREUSE DE BASKET-BALL')),
    ('NAQ0023028', 'CO CHATELUS MALVALEIX', '23270', 'CHATELUS-MALVALEIX', (SELECT id FROM committees WHERE name = 'COMITE DE LA CREUSE DE BASKET-BALL')),
    ('NAQ0023030', 'BASKET CLUB CHAMBON EVAUX', '23170', 'CHAMBON-SUR-VOUEIZE', (SELECT id FROM committees WHERE name = 'COMITE DE LA CREUSE DE BASKET-BALL')),
    ('NAQ0023034', 'BASKET CLUB ST VAURY', '23320', 'SAINT-VAURY', (SELECT id FROM committees WHERE name = 'COMITE DE LA CREUSE DE BASKET-BALL')),
    ('NAQ0023038', 'ENTENTE BC DUN - LA SOUTERRAIN BASKET BALL', '23800', 'DUN-LE-PALESTEL', (SELECT id FROM committees WHERE name = 'COMITE DE LA CREUSE DE BASKET-BALL'));
