INSERT INTO clubs (code, name, zip_code, city, committee_id)
VALUES
    ('BFC0025001', 'CD DOUBS HORS ASSOCIATION', '25000', 'BESANCON', (SELECT id FROM committees WHERE name = 'COMITE DU DOUBS DE BASKET-BALL')),
    ('BFC0025003', 'BESANCON AVENIR COMTOIS', '25000', 'BESANCON', (SELECT id FROM committees WHERE name = 'COMITE DU DOUBS DE BASKET-BALL')),
    ('BFC0025005', 'CA PONTARLIER BASKETBALL', '25300', 'PONTARLIER', (SELECT id FROM committees WHERE name = 'COMITE DU DOUBS DE BASKET-BALL')),
    ('BFC0025007', 'ARC ET SENANS BASKET CLUB', '25610', 'ARC-ET-SENANS', (SELECT id FROM committees WHERE name = 'COMITE DU DOUBS DE BASKET-BALL')),
    ('BFC0025009', 'ASSOCIATION BISONTINE VAUBAN BASKET', '25000', 'BESANCON', (SELECT id FROM committees WHERE name = 'COMITE DU DOUBS DE BASKET-BALL')),
    ('BFC0025011', 'AS EXINCOURT', '25400', 'EXINCOURT', (SELECT id FROM committees WHERE name = 'COMITE DU DOUBS DE BASKET-BALL')),
    ('BFC0025012', 'STAR BASKET SAINT-VIT', '25410', 'SAINT-VIT', (SELECT id FROM committees WHERE name = 'COMITE DU DOUBS DE BASKET-BALL')),
    ('BFC0025016', 'AS VALDAHON', '25800', 'VALDAHON', (SELECT id FROM committees WHERE name = 'COMITE DU DOUBS DE BASKET-BALL')),
    ('BFC0025019', 'P.I.SAONE VALLEE D''ORNANS BASKET', '25660', 'SAONE', (SELECT id FROM committees WHERE name = 'COMITE DU DOUBS DE BASKET-BALL')),
    ('BFC0025023', 'AS VALENTIGNEY BASKET', '25400', 'AUDINCOURT', (SELECT id FROM committees WHERE name = 'COMITE DU DOUBS DE BASKET-BALL')),
    ('BFC0025028', 'BAUME LES DAMES BASKETBALL', '25110', 'BAUME-LES-DAMES', (SELECT id FROM committees WHERE name = 'COMITE DU DOUBS DE BASKET-BALL')),
    ('BFC0025029', 'VAL DE MORTEAU BASKET', '25130', 'VILLERS-LE-LAC', (SELECT id FROM committees WHERE name = 'COMITE DU DOUBS DE BASKET-BALL')),
    ('BFC0025031', 'BASKET CLUB L''ISLOIS', '25250', 'ISLE-SUR-LE-DOUBS', (SELECT id FROM committees WHERE name = 'COMITE DU DOUBS DE BASKET-BALL')),
    ('BFC0025038', 'THISE DEVECEY BASKET CLUB', '25870', 'VIEILLEY', (SELECT id FROM committees WHERE name = 'COMITE DU DOUBS DE BASKET-BALL'));
