INSERT INTO clubs (code, name, zip_code, city, committee_id)
VALUES
    ('COR002A003', 'ATHLETIC CLUB AJACCIEN BASKET-BALL', '20090', 'AJACCIO', (SELECT id FROM committees WHERE name = 'COMITE DE LA CORSE DU SUD DE BASKET-BALL')),
    ('COR002A004', 'PROPRIANO BASKET BALL', '20110', 'ARBELLARA', (SELECT id FROM committees WHERE name = 'COMITE DE LA CORSE DU SUD DE BASKET-BALL')),
    ('COR002A105', 'AJACCIO BASKET CLUB', '20167', 'ALATA', (SELECT id FROM committees WHERE name = 'COMITE DE LA CORSE DU SUD DE BASKET-BALL')),
    ('COR002A113', 'AS PORTO VECCHIO BASKET BALL', '20137', 'PORTO-VECCHIO', (SELECT id FROM committees WHERE name = 'COMITE DE LA CORSE DU SUD DE BASKET-BALL')),
    ('COR002A133', 'BB CLUB DE SAINTE LUCIE DE PORTO VECCHIO (BBCSL)', '20124', 'ZONZA', (SELECT id FROM committees WHERE name = 'COMITE DE LA CORSE DU SUD DE BASKET-BALL')),
    ('COR002A135', 'GFC AJACCIO BASKET BALL', '20090', 'AJACCIO', (SELECT id FROM committees WHERE name = 'COMITE DE LA CORSE DU SUD DE BASKET-BALL'));
