INSERT INTO clubs (code, name, zip_code, city, committee_id)
VALUES
    ('COR002B001', 'COMITE HORS ASSOCIATION DE CORSE', '20250', 'CORTE', (SELECT id FROM committees WHERE name = 'COMITE DE LA HAUTE-CORSE DE BASKET-BALL')),
    ('COR002B002', 'ETOILE FILANTE O BASTIA BB', '20200', 'SANTA-MARIA-DI-LOTA', (SELECT id FROM committees WHERE name = 'COMITE DE LA HAUTE-CORSE DE BASKET-BALL')),
    ('COR002B006', 'INTER CORTENAIS', '20250', 'CORTE', (SELECT id FROM committees WHERE name = 'COMITE DE LA HAUTE-CORSE DE BASKET-BALL')),
    ('COR002B007', 'VESCOVATO CASINCA BASKET BALL', '20213', 'CASTELLARE-DI-CASINCA', (SELECT id FROM committees WHERE name = 'COMITE DE LA HAUTE-CORSE DE BASKET-BALL')),
    ('COR002B008', 'BASKET-BALL GHISONACCIA', '20240', 'GHISONACCIA', (SELECT id FROM committees WHERE name = 'COMITE DE LA HAUTE-CORSE DE BASKET-BALL')),
    ('COR002B009', 'UNION CASINCA CENTRE CORSE BASKETBALL', '20290', 'BORGO', (SELECT id FROM committees WHERE name = 'COMITE DE LA HAUTE-CORSE DE BASKET-BALL')),
    ('COR002B010', 'FURIANI BASKET CLUB', '20600', 'BASTIA', (SELECT id FROM committees WHERE name = 'COMITE DE LA HAUTE-CORSE DE BASKET-BALL')),
    ('COR002B012', 'CLUB OMNISPORTS COSTA VERDE', '20221', 'VALLE-DI-CAMPOLORO', (SELECT id FROM committees WHERE name = 'COMITE DE LA HAUTE-CORSE DE BASKET-BALL')),
    ('COR002B018', 'SELECTION REGIONALE CORSE', '20250', 'CORTE', (SELECT id FROM committees WHERE name = 'COMITE DE LA HAUTE-CORSE DE BASKET-BALL')),
    ('COR002B019', 'GHJUVENTU BASKET BORGO', '20290', 'LUCCIANA', (SELECT id FROM committees WHERE name = 'COMITE DE LA HAUTE-CORSE DE BASKET-BALL'));
