INSERT INTO clubs (code, name, zip_code, city, committee_id)
VALUES
    ('BFC0039001', 'CD JURA HORS ASSOCIATION', 39250, 'DOYE', (SELECT id FROM committees WHERE name = 'COMITE DU JURA DE BASKET-BALL')),
    ('BFC0039002', 'SAINT AMOUR BASKET', 39160, 'SAINT-AMOUR', (SELECT id FROM committees WHERE name = 'COMITE DU JURA DE BASKET-BALL')),
    ('BFC0039003', 'POLIGNY JURA BASKET COMTE', 39800, 'POLIGNY', (SELECT id FROM committees WHERE name = 'COMITE DU JURA DE BASKET-BALL')),
    ('BFC0039004', 'JURA DOLOIS BASKET', 39100, 'DOLE', (SELECT id FROM committees WHERE name = 'COMITE DU JURA DE BASKET-BALL')),
    ('BFC0039005', 'EVEIL SPORTIF MONTMOROT', 39570, 'MONTMOROT', (SELECT id FROM committees WHERE name = 'COMITE DU JURA DE BASKET-BALL')),
    ('BFC0039006', 'BASKET CUVIER FRASNE', 39250, 'CUVIER', (SELECT id FROM committees WHERE name = 'COMITE DU JURA DE BASKET-BALL')),
    ('BFC0039007', 'AMICALE LAÏQUE LÉDONIENNE JURA BASKET', 39000, 'LONS-LE-SAUNIER', (SELECT id FROM committees WHERE name = 'COMITE DU JURA DE BASKET-BALL')),
    ('BFC0039010', 'CHAMPAGNOLE JURA BASKET', 39300, 'CHAMPAGNOLE', (SELECT id FROM committees WHERE name = 'COMITE DU JURA DE BASKET-BALL')),
    ('BFC0039011', 'HAUT JURA BASKET ST CLAUDE', 39200, 'SAINT-CLAUDE', (SELECT id FROM committees WHERE name = 'COMITE DU JURA DE BASKET-BALL')),
    ('BFC0039014', 'JURA SALINS BASKET CLUB', 39110, 'SALINS-LES-BAINS', (SELECT id FROM committees WHERE name = 'COMITE DU JURA DE BASKET-BALL')),
    ('BFC0039016', 'BASKET CLUB CLAIRVAUX LES LACS', 39130, 'CLAIRVAUX-LES-LACS', (SELECT id FROM committees WHERE name = 'COMITE DU JURA DE BASKET-BALL')),
    ('BFC0039017', 'BASKET ORGELET CLUB', 39270, 'ORGELET', (SELECT id FROM committees WHERE name = 'COMITE DU JURA DE BASKET-BALL')),
    ('BFC0039021', 'MOREZIENS BASKET CLUB', 39400, 'MOREZ', (SELECT id FROM committees WHERE name = 'COMITE DU JURA DE BASKET-BALL')),
    ('BFC0039022', 'ENT CHAMPAGNOLE POLIGNY', 39300, 'CHAMPAGNOLE', (SELECT id FROM committees WHERE name = 'COMITE DU JURA DE BASKET-BALL'));
