INSERT INTO clubs (zip_code, code, name, city, committee_id)
VALUES
    ('46000', 'OCC0046001', 'CT QUERCY GARONNE HORS ASSOCIATION', 'CAHORS', (SELECT id FROM committees WHERE name = 'COMITE DU LOT de BASKET-BALL')),
    ('46000', 'OCC0046003', 'CAHORSAUZET BASKET', 'CAHORS', (SELECT id FROM committees WHERE name = 'COMITE DU LOT de BASKET-BALL')),
    ('46090', 'OCC0046007', 'ESPERE - BASKET', 'ESPERE', (SELECT id FROM committees WHERE name = 'COMITE DU LOT de BASKET-BALL')),
    ('46220', 'OCC0046009', 'PRAYSSAC BASKET CLUB', 'PRAYSSAC', (SELECT id FROM committees WHERE name = 'COMITE DU LOT de BASKET-BALL')),
    ('46800', 'OCC0046011', 'MONTCUQ BASKET', 'MONTCUQ', (SELECT id FROM committees WHERE name = 'COMITE DU LOT de BASKET-BALL')),
    ('46090', 'OCC0046022', 'PRADINES LOT BASKET', 'PRADINES', (SELECT id FROM committees WHERE name = 'COMITE DU LOT de BASKET-BALL')),
    ('46230', 'OCC0046027', 'BASKET CLUB LALBENQUE', 'LALBENQUE', (SELECT id FROM committees WHERE name = 'COMITE DU LOT de BASKET-BALL')),
    ('46340', 'OCC0046034', 'SALVIAC BASKET CLUB', 'SALVIAC', (SELECT id FROM committees WHERE name = 'COMITE DU LOT de BASKET-BALL')),
    ('46230', 'OCC0046036', 'Entente LALBENQUE MONTPEZAT', 'LALBENQUE', (SELECT id FROM committees WHERE name = 'COMITE DU LOT de BASKET-BALL')),
    ('46090', 'OCC0046038', 'Entente Espère Prayssac', 'ESPERE', (SELECT id FROM committees WHERE name = 'COMITE DU LOT de BASKET-BALL'));