INSERT INTO clubs (zip_code, code, name, city, committee_id)
VALUES
    ('52000', 'GES0052503', 'ENTENTE CHAUMONTAISE AC BASKET', 'CHAUMONT', (SELECT id FROM committees WHERE name = 'COMITE DE L''HAUTE-MARNE DE BASKET-BALL')),
    ('52100', 'GES0052507', 'SAINT DIZIER BASKET', 'SAINT-DIZIER', (SELECT id FROM committees WHERE name = 'COMITE DE L''HAUTE-MARNE DE BASKET-BALL')),
    ('52130', 'GES0052508', 'AS BASKET WASSEYEN', 'ATTANCOURT', (SELECT id FROM committees WHERE name = 'COMITE DE L''HAUTE-MARNE DE BASKET-BALL')),
    ('52200', 'GES0052509', 'LANGRES BASKET CLUB', 'LANGRES', (SELECT id FROM committees WHERE name = 'COMITE DE L''HAUTE-MARNE DE BASKET-BALL'));