INSERT INTO clubs (code, name, zip_code, city, committee_id)
VALUES
    ('GES0055001', 'CD 55 HORS ASSOCIATION', '55100', 'VERDUN', (SELECT id FROM committees WHERE name = 'COMITE DE LA MEUSE DE BASKET-BALL')),
    ('GES0055002', 'MJC ANCERVILLE', '55170', 'ANCERVILLE', (SELECT id FROM committees WHERE name = 'COMITE DE LA MEUSE DE BASKET-BALL')),
    ('GES0055003', 'CSLB BAR LE DUC', '55000', 'BAR-LE-DUC', (SELECT id FROM committees WHERE name = 'COMITE DE LA MEUSE DE BASKET-BALL')),
    ('GES0055007', 'SAINT-MIHIEL-SPORT BASKET-BALL', '55300', 'SAINT-MIHIEL', (SELECT id FROM committees WHERE name = 'COMITE DE LA MEUSE DE BASKET-BALL')),
    ('GES0055009', 'AS SOUILLY-BASKET', '55220', 'SOUILLY', (SELECT id FROM committees WHERE name = 'COMITE DE LA MEUSE DE BASKET-BALL')),
    ('GES0055010', 'BCV VERDUN', '55100', 'VERDUN', (SELECT id FROM committees WHERE name = 'COMITE DE LA MEUSE DE BASKET-BALL')),
    ('GES0055012', 'AVENIR DE VIGNOT', '55200', 'VIGNOT', (SELECT id FROM committees WHERE name = 'COMITE DE LA MEUSE DE BASKET-BALL')),
    ('GES0055013', 'ASC CHARNY SUR MEUSE', '55100', 'CHARNY-SUR-MEUSE', (SELECT id FROM committees WHERE name = 'COMITE DE LA MEUSE DE BASKET-BALL')),
    ('GES0055016', 'L''ESPERANCE DE STENAY', '55700', 'STENAY', (SELECT id FROM committees WHERE name = 'COMITE DE LA MEUSE DE BASKET-BALL')),
    ('GES0055020', 'REVIGNY BASKET CLUB', '55000', 'BAR-LE-DUC', (SELECT id FROM committees WHERE name = 'COMITE DE LA MEUSE DE BASKET-BALL')),
    ('GES0055025', 'PAGNY SUR MEUSE BC', '55190', 'PAGNY-SUR-MEUSE', (SELECT id FROM committees WHERE name = 'COMITE DE LA MEUSE DE BASKET-BALL'));
