INSERT INTO clubs (code, name, zip_code, city, committee_id)
VALUES
    ('BFC0058001', 'CD 58 HORS ASSOCIATION', '58000', 'NEVERS', (SELECT id FROM committees WHERE name = 'COMITE DE LA NIEVRE DE BASKET-BALL')),
    ('BFC0058003', 'BC COULANGES LES NEVERS', '58660', 'COULANGES-LES-NEVERS', (SELECT id FROM committees WHERE name = 'COMITE DE LA NIEVRE DE BASKET-BALL')),
    ('BFC0058004', 'U COSNOISE S BASKET', '58200', 'COSNE-COURS-SUR-LOIRE', (SELECT id FROM committees WHERE name = 'COMITE DE LA NIEVRE DE BASKET-BALL')),
    ('BFC0058007', 'DORNES BASKET', '58390', 'DORNES', (SELECT id FROM committees WHERE name = 'COMITE DE LA NIEVRE DE BASKET-BALL')),
    ('BFC0058009', 'EB FOURCHAMBAULT NEVERS', '58000', 'NEVERS', (SELECT id FROM committees WHERE name = 'COMITE DE LA NIEVRE DE BASKET-BALL')),
    ('BFC0058011', 'US CHARITOISE BASKET', '58400', 'CHARITE-SUR-LOIRE', (SELECT id FROM committees WHERE name = 'COMITE DE LA NIEVRE DE BASKET-BALL')),
    ('BFC0058013', 'JS MARZY BASKET', '58180', 'MARZY', (SELECT id FROM committees WHERE name = 'COMITE DE LA NIEVRE DE BASKET-BALL')),
    ('BFC0058014', 'BASKET CLUB SAINT PIERROIS', '58240', 'SAINT-PIERRE-LE-MOUTIER', (SELECT id FROM committees WHERE name = 'COMITE DE LA NIEVRE DE BASKET-BALL')),
    ('BFC0058015', 'ASC DE NEUVY SUR LOIRE', '58450', 'NEUVY-SUR-LOIRE', (SELECT id FROM committees WHERE name = 'COMITE DE LA NIEVRE DE BASKET-BALL')),
    ('BFC0058016', 'A POUGUOISE DE BASKET B', '58320', 'POUGUES-LES-EAUX', (SELECT id FROM committees WHERE name = 'COMITE DE LA NIEVRE DE BASKET-BALL')),
    ('BFC0058017', 'ETOILE SPORTIVE DONZIAISE BASKET', '58220', 'DONZY', (SELECT id FROM committees WHERE name = 'COMITE DE LA NIEVRE DE BASKET-BALL')),
    ('BFC0058018', 'CLUB JEUNES PUISAYE FORTERRE', '58310', 'SAINT-AMAND-EN-PUISAYE', (SELECT id FROM committees WHERE name = 'COMITE DE LA NIEVRE DE BASKET-BALL')),
    ('BFC0058019', 'A S A VAUZELLES', '58640', 'VARENNES-VAUZELLES', (SELECT id FROM committees WHERE name = 'COMITE DE LA NIEVRE DE BASKET-BALL')),
    ('BFC0058020', 'ESPERANCE CORVOL BASKET', '58460', 'CORVOL-L''ORGUEILLEUX', (SELECT id FROM committees WHERE name = 'COMITE DE LA NIEVRE DE BASKET-BALL')),
    ('BFC0058022', 'AS GUERIGNY URZY SECTION BASKET', '58130', 'GUERIGNY', (SELECT id FROM committees WHERE name = 'COMITE DE LA NIEVRE DE BASKET-BALL')),
    ('BFC0058038', 'ENTENTE JS MARZY - DORNES BASKET', '58180', 'MARZY', (SELECT id FROM committees WHERE name = 'COMITE DE LA NIEVRE DE BASKET-BALL'));
