INSERT INTO clubs (code, name, zip_code, city, committee_id)
VALUES
    ('NOR0061001', 'CD HORS ASSOCIATION', '61000', 'ALENCON', (SELECT id FROM committees WHERE name = 'COMITE DE L''ORNE DE BASKET-BALL')),
    ('NOR0061002', 'UNION SPORTIVE BASKET DAMIGNY ALENCON 61 (USBDA61)', '61000', 'ALENCON', (SELECT id FROM committees WHERE name = 'COMITE DE L''ORNE DE BASKET-BALL')),
    ('NOR0061003', 'BAYARD ARGENTAN', '61200', 'ARGENTAN', (SELECT id FROM committees WHERE name = 'COMITE DE L''ORNE DE BASKET-BALL')),
    ('NOR0061004', 'PATRONAGE LAIQUE D''ARGENTAN', '61200', 'ARGENTAN', (SELECT id FROM committees WHERE name = 'COMITE DE L''ORNE DE BASKET-BALL')),
    ('NOR0061005', 'BASKET FLERS SAINT GEORGES', '61100', 'SAINT-GEORGES-DES-GROSEILLERS', (SELECT id FROM committees WHERE name = 'COMITE DE L''ORNE DE BASKET-BALL')),
    ('NOR0061007', 'OLYMPIQUE CLUB DE BRIOUZE', '61220', 'BRIOUZE', (SELECT id FROM committees WHERE name = 'COMITE DE L''ORNE DE BASKET-BALL')),
    ('NOR0061008', 'BASKET CLUB DU PAYS DE LA RISLE', '61270', 'RAI', (SELECT id FROM committees WHERE name = 'COMITE DE L''ORNE DE BASKET-BALL')),
    ('NOR0061014', 'Association Basket Club de Mortagne', '61400', 'MORTAGNE-AU-PERCHE', (SELECT id FROM committees WHERE name = 'COMITE DE L''ORNE DE BASKET-BALL')),
    ('NOR0061015', 'BASKET CLUB DU PAYS MELOIS', '61170', 'MELE-SUR-SARTHE', (SELECT id FROM committees WHERE name = 'COMITE DE L''ORNE DE BASKET-BALL')),
    ('NOR0061018', 'LES BASKETTEURS GACEENS', '61230', 'GACE', (SELECT id FROM committees WHERE name = 'COMITE DE L''ORNE DE BASKET-BALL')),
    ('NOR0061019', 'BASKET CLUB DE SEES', '61500', 'SEES', (SELECT id FROM committees WHERE name = 'COMITE DE L''ORNE DE BASKET-BALL')),
    ('NOR0061023', 'AVENIR ST GERMAIN DU CORBEIS BA', '61000', 'SAINT-GERMAIN-DU-CORBEIS', (SELECT id FROM committees WHERE name = 'COMITE DE L''ORNE DE BASKET-BALL')),
    ('NOR0061025', 'BASKET BALL FERTOIS', '61600', 'Ferté Macé (La)', (SELECT id FROM committees WHERE name = 'COMITE DE L''ORNE DE BASKET-BALL')),
    ('NOR0061026', 'BASKET SAINT PIERRE DU REGARD', '61430', 'ATHIS-VAL-DE-ROUVRE', (SELECT id FROM committees WHERE name = 'COMITE DE L''ORNE DE BASKET-BALL'));
