INSERT INTO clubs (zip_code, code, name, city, committee_id)
VALUES
    ('70000', 'BFC0070001', 'CD70/90 – HAUTE SAONE ET TERRITOIRE DE BELFORT BASKET BALL', 'VESOUL', (SELECT id FROM committees WHERE name = 'COMITE DE HAUTE-SAONE DE BASKET-BALL')),
    ('70220', 'BFC0070002', 'FOUGEROLLES BC', 'FOUGEROLLES', (SELECT id FROM committees WHERE name = 'COMITE DE HAUTE-SAONE DE BASKET-BALL')),
    ('70000', 'BFC0070003', 'AVANT GARDE de la MOTTE VESOUL', 'VESOUL', (SELECT id FROM committees WHERE name = 'COMITE DE HAUTE-SAONE DE BASKET-BALL')),
    ('70100', 'BFC0070004', 'VAL DE GRAY BASKET', 'ARC-LES-GRAY', (SELECT id FROM committees WHERE name = 'COMITE DE HAUTE-SAONE DE BASKET-BALL')),
    ('70400', 'BFC0070005', 'SPORTS GENERAUX HERICOURT BASKET', 'HERICOURT', (SELECT id FROM committees WHERE name = 'COMITE DE HAUTE-SAONE DE BASKET-BALL')),
    ('70800', 'BFC0070006', 'ST LOUP FC', 'SAINT-LOUP-SUR-SEMOUSE', (SELECT id FROM committees WHERE name = 'COMITE DE HAUTE-SAONE DE BASKET-BALL')),
    ('70300', 'BFC0070007', 'AL LUXEUIL', 'LUXEUIL-LES-BAINS', (SELECT id FROM committees WHERE name = 'COMITE DE HAUTE-SAONE DE BASKET-BALL')),
    ('70200', 'BFC0070008', 'LURE BC', 'MAGNY-VERNOIS', (SELECT id FROM committees WHERE name = 'COMITE DE HAUTE-SAONE DE BASKET-BALL')),
    ('70170', 'BFC0070009', 'PORT SUR SAONE', 'PORT-SUR-SAONE', (SELECT id FROM committees WHERE name = 'COMITE DE HAUTE-SAONE DE BASKET-BALL')),
    ('70500', 'BFC0070011', 'BASKET BALL JUSSEEN', 'JUSSEY', (SELECT id FROM committees WHERE name = 'COMITE DE HAUTE-SAONE DE BASKET-BALL')),
    ('70400', 'BFC0070026', 'CHENEVIERE BASKET HERICOURT', 'HERICOURT', (SELECT id FROM committees WHERE name = 'COMITE DE HAUTE-SAONE DE BASKET-BALL'));