INSERT INTO clubs (zip_code, code, name, city, committee_id)
VALUES
    ('82370', 'OCC0082032', 'BASKET CLUB BASTIDIEN', 'LABASTIDE-SAINT-PIERRE', (SELECT id FROM committees WHERE name = 'COMITE DE TARN-ET-GARONNE de BASKET-BALL')),
    ('82700', 'OCC0082040', 'Montech Montauban Basket Ball', 'MONTECH', (SELECT id FROM committees WHERE name = 'COMITE DE TARN-ET-GARONNE de BASKET-BALL')),
    ('82220', 'OCC0082503', 'SA CAUSSADE', 'AUTY', (SELECT id FROM committees WHERE name = 'COMITE DE TARN-ET-GARONNE de BASKET-BALL')),
    ('82400', 'OCC0082504', 'BASKET CLUB GOLFECHOIS', 'GOLFECH', (SELECT id FROM committees WHERE name = 'COMITE DE TARN-ET-GARONNE de BASKET-BALL')),
    ('82200', 'OCC0082507', 'MOISSAC CASTELSARRASIN BB', 'MOISSAC', (SELECT id FROM committees WHERE name = 'COMITE DE TARN-ET-GARONNE de BASKET-BALL')),
    ('82000', 'OCC0082509', 'MONTAUBAN BASKET CLUB', 'MONTAUBAN', (SELECT id FROM committees WHERE name = 'COMITE DE TARN-ET-GARONNE de BASKET-BALL')),
    ('82270', 'OCC0082511', 'BC MONTPEZAT DE QUERCY', 'MONTPEZAT-DE-QUERCY', (SELECT id FROM committees WHERE name = 'COMITE DE TARN-ET-GARONNE de BASKET-BALL')),
    ('82800', 'OCC0082512', 'GIMBELET BASKET CLUB', 'NEGREPELISSE', (SELECT id FROM committees WHERE name = 'COMITE DE TARN-ET-GARONNE de BASKET-BALL')),
    ('82370', 'OCC0082514', 'ST NAUPHARY ACO', 'SAINT-NAUPHARY', (SELECT id FROM committees WHERE name = 'COMITE DE TARN-ET-GARONNE de BASKET-BALL')),
    ('82210', 'OCC0082515', 'AMICALE LAIQUE ST NICOLAS BASKET', 'SAINT-NICOLAS-DE-LA-GRAVE', (SELECT id FROM committees WHERE name = 'COMITE DE TARN-ET-GARONNE de BASKET-BALL')),
    ('82220', 'OCC0082516', 'VAZERAC SUD QUERCY BASKET', 'VAZERAC', (SELECT id FROM committees WHERE name = 'COMITE DE TARN-ET-GARONNE de BASKET-BALL')),
    ('82700', 'OCC0082519', 'AS ST PORQUIER', 'SAINT-PORQUIER', (SELECT id FROM committees WHERE name = 'COMITE DE TARN-ET-GARONNE de BASKET-BALL')),
    ('82170', 'OCC0082521', 'BLEUETS DE GRISOLLES', 'GRISOLLES', (SELECT id FROM committees WHERE name = 'COMITE DE TARN-ET-GARONNE de BASKET-BALL')),
    ('82100', 'OCC0082525', 'LABASTIDE DU TEMPLE BASKET', 'LABASTIDE-DU-TEMPLE', (SELECT id FROM committees WHERE name = 'COMITE DE TARN-ET-GARONNE de BASKET-BALL')),
    ('82700', 'OCC0082535', 'MONTECH BASKET BALL', 'MONTECH', (SELECT id FROM committees WHERE name = 'COMITE DE TARN-ET-GARONNE de BASKET-BALL'));
