INSERT INTO clubs (zip_code, code, name, city, committee_id)
VALUES
    ('90100', 'BFC0090014', 'ASSOCIATION BASKET CLUB DELLE', 'LEBETAIN', (SELECT id FROM committees WHERE name = 'COMITE DU TERRITOIRE-DE-BELFORT DE BASKET-BALL')),
    ('90000', 'BFC0090015', 'BC BELFORT', 'BELFORT', (SELECT id FROM committees WHERE name = 'COMITE DU TERRITOIRE-DE-BELFORT DE BASKET-BALL')),
    ('90300', 'BFC0090016', 'BC VAL D''OYE', 'VALDOIE', (SELECT id FROM committees WHERE name = 'COMITE DU TERRITOIRE-DE-BELFORT DE BASKET-BALL')),
    ('90300', 'BFC0090017', 'ASM BELFORT', 'CRAVANCHE', (SELECT id FROM committees WHERE name = 'COMITE DU TERRITOIRE-DE-BELFORT DE BASKET-BALL'));
