INSERT INTO clubs (zip_code, code, name, city, committee_id)
VALUES
    ('97300', 'GUY0973001', 'CD HORS ASSOCIATIONS', 'CAYENNE', (SELECT id FROM committees WHERE name = 'COMITE DE LA GUYANE DE BASKET-BALL')),
    ('97300', 'GUY0973003', 'ASL SPORT GUYANAIS', 'CAYENNE', (SELECT id FROM committees WHERE name = 'COMITE DE LA GUYANE DE BASKET-BALL')),
    ('97351', 'GUY0973005', 'UNION SPORTIVE AMERIQUE DU SUD', 'MATOURY', (SELECT id FROM committees WHERE name = 'COMITE DE LA GUYANE DE BASKET-BALL')),
    ('97300', 'GUY0973007', 'ASC LE CYGNE', 'CAYENNE', (SELECT id FROM committees WHERE name = 'COMITE DE LA GUYANE DE BASKET-BALL')),
    ('97354', 'GUY0973009', 'USL MONTJOLY', 'REMIRE-MONTJOLY', (SELECT id FROM committees WHERE name = 'COMITE DE LA GUYANE DE BASKET-BALL')),
    ('97315', 'GUY0973011', 'US SINNAMARY', 'SINNAMARY', (SELECT id FROM committees WHERE name = 'COMITE DE LA GUYANE DE BASKET-BALL')),
    ('97351', 'GUY0973015', 'ASC MATOURY 88', 'MATOURY', (SELECT id FROM committees WHERE name = 'COMITE DE LA GUYANE DE BASKET-BALL')),
    ('97300', 'GUY0973017', 'ASC TOURS', 'CAYENNE', (SELECT id FROM committees WHERE name = 'COMITE DE LA GUYANE DE BASKET-BALL')),
    ('97320', 'GUY0973019', 'COS MARONI BASKET BALL', 'SAINT-LAURENT-DU-MARONI', (SELECT id FROM committees WHERE name = 'COMITE DE LA GUYANE DE BASKET-BALL')),
    ('97300', 'GUY0973020', 'MAGIC TEAM', 'CAYENNE', (SELECT id FROM committees WHERE name = 'COMITE DE LA GUYANE DE BASKET-BALL')),
    ('97310', 'GUY0973021', 'ASC ROU..KOU', 'KOUROU', (SELECT id FROM committees WHERE name = 'COMITE DE LA GUYANE DE BASKET-BALL')),
    ('97355', 'GUY0973027', 'ASAM', 'MACOURIA', (SELECT id FROM committees WHERE name = 'COMITE DE LA GUYANE DE BASKET-BALL')),
    ('97360', 'GUY0973033', 'MANA. BASKET. ASSOCIATION', 'MANA', (SELECT id FROM committees WHERE name = 'COMITE DE LA GUYANE DE BASKET-BALL'));
