INSERT INTO clubs (zip_code, code, name, city, committee_id)
VALUES
    ('97150', 'GUA0978002', 'LET''S DO IT LDI', 'SAINT-MARTIN', (SELECT id FROM committees WHERE name = 'COMITE DE SAINT-MARTIN DE BASKET-BALL')),
    ('97150', 'GUA0978004', 'ASSOCIATION SPORTIVE DE PHOENICKS', 'SAINT-MARTIN', (SELECT id FROM committees WHERE name = 'COMITE DE SAINT-MARTIN DE BASKET-BALL')),
    ('97150', 'GUA0978094', 'CTBIN HORS ASSOCIATION', 'SAINT-MARTIN', (SELECT id FROM committees WHERE name = 'COMITE DE SAINT-MARTIN DE BASKET-BALL')),
    ('97150', 'GUA0978124', 'RCM BALLERS', 'SAINT-MARTIN', (SELECT id FROM committees WHERE name = 'COMITE DE SAINT-MARTIN DE BASKET-BALL')),
    ('97150', 'GUA0978128', 'BOYS IN THE YARD', 'SAINT-MARTIN', (SELECT id FROM committees WHERE name = 'COMITE DE SAINT-MARTIN DE BASKET-BALL'));