INSERT INTO clubs (zip_code, code, name, city, committee_id)
VALUES
    ('98600', 'WEF0986001', 'HORIZONS 02 BASKET CLUB', 'UVEA', (SELECT id FROM committees WHERE name = 'COMITE DE WALLIS-ET-FUTUNA DE BASKET-BALL')),
    ('98600', 'WEF0986020', 'JEUNESSE SPORTIVE DE WALLIS', 'UVEA', (SELECT id FROM committees WHERE name = 'COMITE DE WALLIS-ET-FUTUNA DE BASKET-BALL'));
