INSERT INTO clubs (zip_code, code, name, city, committee_id)
VALUES
    ('98701', 'PFR0987002', 'AS ARUE', 'ARUE', (SELECT id FROM committees WHERE name = 'COMITE DE POLYNESIE-FRANCAISE - ARCHIPEL DE LA SOCIÉTÉ DE BASKET-BALL')),
    ('98712', 'PFR0987003', 'PAPARA BASKET CLUB', 'PAPARA', (SELECT id FROM committees WHERE name = 'COMITE DE POLYNESIE-FRANCAISE - ARCHIPEL DE LA SOCIÉTÉ DE BASKET-BALL')),
    ('98701', 'PFR0987006', 'AS FEI PI', 'ARUE', (SELECT id FROM committees WHERE name = 'COMITE DE POLYNESIE-FRANCAISE - ARCHIPEL DE LA SOCIÉTÉ DE BASKET-BALL')),
    ('98716', 'PFR0987007', 'AS JT', 'PIRAE', (SELECT id FROM committees WHERE name = 'COMITE DE POLYNESIE-FRANCAISE - ARCHIPEL DE LA SOCIÉTÉ DE BASKET-BALL')),
    ('98717', 'PFR0987008', 'AS PUNARUU', 'PUNAAUIA', (SELECT id FROM committees WHERE name = 'COMITE DE POLYNESIE-FRANCAISE - ARCHIPEL DE LA SOCIÉTÉ DE BASKET-BALL')),
    ('98713', 'PFR0987009', 'AS AORAI', 'PAPEETE', (SELECT id FROM committees WHERE name = 'COMITE DE POLYNESIE-FRANCAISE - ARCHIPEL DE LA SOCIÉTÉ DE BASKET-BALL')),
    ('98713', 'PFR0987010', 'AS CENTRAL SPORTS', 'PAPEETE', (SELECT id FROM committees WHERE name = 'COMITE DE POLYNESIE-FRANCAISE - ARCHIPEL DE LA SOCIÉTÉ DE BASKET-BALL')),
    ('98719', 'PFR0987012', 'AS TAMARII TARAVAO', 'TARAVAO', (SELECT id FROM committees WHERE name = 'COMITE DE POLYNESIE-FRANCAISE - ARCHIPEL DE LA SOCIÉTÉ DE BASKET-BALL')),
    ('98713', 'PFR0987013', 'AS SDJ', 'PAPEETE', (SELECT id FROM committees WHERE name = 'COMITE DE POLYNESIE-FRANCAISE - ARCHIPEL DE LA SOCIÉTÉ DE BASKET-BALL')),
    ('98711', 'PFR0987014', 'AS MANU URA PAEA', 'PAEA', (SELECT id FROM committees WHERE name = 'COMITE DE POLYNESIE-FRANCAISE - ARCHIPEL DE LA SOCIÉTÉ DE BASKET-BALL')),
    ('98713', 'PFR0987018', 'AS DRAGON', 'PAPEETE', (SELECT id FROM committees WHERE name = 'COMITE DE POLYNESIE-FRANCAISE - ARCHIPEL DE LA SOCIÉTÉ DE BASKET-BALL')),
    ('98704', 'PFR0987019', 'AS TEFANA', 'FAAA', (SELECT id FROM committees WHERE name = 'COMITE DE POLYNESIE-FRANCAISE - ARCHIPEL DE LA SOCIÉTÉ DE BASKET-BALL')),
    ('98714', 'PFR0987211', 'AS EXCELSIOR', 'PAPEETE TAHITI', (SELECT id FROM committees WHERE name = 'COMITE DE POLYNESIE-FRANCAISE - ARCHIPEL DE LA SOCIÉTÉ DE BASKET-BALL'));
    