INSERT INTO clubs (zip_code, code, name, city, committee_id)
VALUES
    ('98809', 'NCA0988002', 'MONT DORE BASKET CLUB', 'LE MONT DORE', (SELECT id FROM committees WHERE name = 'COMITE DE NOUVELLE CALEDONIE DE BASKET-BALL')),
    ('98800', 'NCA0988003', 'OLYMPIQUE DE NOUMEA', 'NOUMEA', (SELECT id FROM committees WHERE name = 'COMITE DE NOUVELLE CALEDONIE DE BASKET-BALL')),
    ('98800', 'NCA0988005', 'AS RIVIERE SALEE', 'NOUMEA', (SELECT id FROM committees WHERE name = 'COMITE DE NOUVELLE CALEDONIE DE BASKET-BALL')),
    ('98850', 'NCA0988006', 'CLUB SPORTIF BOURAILLAIS', 'NOUVELLE CALEDONIE', (SELECT id FROM committees WHERE name = 'COMITE DE NOUVELLE CALEDONIE DE BASKET-BALL')),
    ('98835', 'NCA0988007', 'JEUNESSE SPORTIVE VALLEE DUTIR', 'DUMBEA', (SELECT id FROM committees WHERE name = 'COMITE DE NOUVELLE CALEDONIE DE BASKET-BALL')),
    ('98800', 'NCA0988008', 'A.S.6 ème Km BB', 'NOUMEA', (SELECT id FROM committees WHERE name = 'COMITE DE NOUVELLE CALEDONIE DE BASKET-BALL')),
    ('98800', 'NCA0988009', 'SOCIETE SPORTIVE INDEPENDANTE', 'NOUMEA', (SELECT id FROM committees WHERE name = 'COMITE DE NOUVELLE CALEDONIE DE BASKET-BALL')),
    ('98800', 'NCA0988010', 'TITANS', 'NOUMEA', (SELECT id FROM committees WHERE name = 'COMITE DE NOUVELLE CALEDONIE DE BASKET-BALL')),
    ('98827', 'NCA0988011', 'ASSOCIATION OMNISPORTS NEPOUI', 'POYA', (SELECT id FROM committees WHERE name = 'COMITE DE NOUVELLE CALEDONIE DE BASKET-BALL')),
    ('98825', 'NCA0988012', 'BASKET CLUB DE POUEMBOUT', 'POUEMBOUT', (SELECT id FROM committees WHERE name = 'COMITE DE NOUVELLE CALEDONIE DE BASKET-BALL')),
    ('98850', 'NCA0988016', 'AS TIEBAGHI', 'KOUMAC', (SELECT id FROM committees WHERE name = 'COMITE DE NOUVELLE CALEDONIE DE BASKET-BALL')),
    ('98800', 'NCA0988024', 'LR NOUVELLE CALEDONIE', 'NOUMEA', (SELECT id FROM committees WHERE name = 'COMITE DE NOUVELLE CALEDONIE DE BASKET-BALL')),
    ('98890', 'NCA0988069', 'BASKETCLUB PAÏTA', 'PAITA', (SELECT id FROM committees WHERE name = 'COMITE DE NOUVELLE CALEDONIE DE BASKET-BALL')),
    ('98835', 'NCA0988070', 'ASDUMBEA', 'DUMBEA', (SELECT id FROM committees WHERE name = 'COMITE DE NOUVELLE CALEDONIE DE BASKET-BALL')),
    ('98822', 'NCA0988081', 'CENTRAL SPORT POINDIMIE', 'POINDIMIE', (SELECT id FROM committees WHERE name = 'COMITE DE NOUVELLE CALEDONIE DE BASKET-BALL')),
    ('98833', 'NCA0988083', 'BASKET CLUB VKP', 'VOH', (SELECT id FROM committees WHERE name = 'COMITE DE NOUVELLE CALEDONIE DE BASKET-BALL'));
